# Generated by Django 3.2.9 on 2021-12-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='lightRequirements',
            new_name='filterByLightRequirements',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='plantSize',
            new_name='filterByPlantSize',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='careLight',
            new_name='light',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='careWater',
            new_name='water',
        ),
    ]
