# Generated by Django 3.2.9 on 2021-12-06 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_user_plant_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='userId',
        ),
    ]
