# Generated by Django 3.2.9 on 2021-12-05 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('countInStock', models.IntegerField(blank=True, default=0, null=True)),
                ('plantSize', models.CharField(blank=True, max_length=30, null=True)),
                ('lightRequirements', models.CharField(blank=True, max_length=30, null=True)),
                ('careLight', models.TextField(blank=True, null=True)),
                ('careWater', models.TextField(blank=True, null=True)),
                ('tips', models.TextField(blank=True, null=True)),
                ('toxicity', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
